version: "3"

services:
  api:
    build:
      context: ./api # Caminho para o diretório contendo o Dockerfile
      dockerfile: Dockerfile
    container_name: container-api
    ports:
      - "3001:3001"
    restart: always

  frontend:
    build:
      context: ./front # Caminho para o diretório contendo o Dockerfile
      dockerfile: Dockerfile
    container_name: container-frontend
    ports:
      - "3000:3000"
    restart: always
